language: rust

rust:
    - beta
    - nightly

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

install:
    - sudo add-apt-repository ppa:team-xbmc/ppa -y
    - sudo apt-get update -q
    - sudo apt-get install libsdl2-dev

before_script:
  - rustc --version
  - cargo -V

script:
  - cargo build -v
